import type { Metadata } from "next";
import localFont from "next/font/local";
import "./scss/globals.scss";

import { Inter, } from "next/font/google";

const inter = Inter({
  weight: ['700', '500', '400'],
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
